# Challenge Problem 07

1. Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100.


Expected Output:
[ 3 5 6 9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51 54
55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
`2318`

In [2]:
import numpy as np

2. Write a NumPy program to create a contiguous flattened array. 

Original array:

```python
[[10 20 30]
[20 40 50]]
```

New flattened array:
```python
[10 20 30 20 40 50]
```

In [5]:
array = np.array([[10, 20, 30],[20, 40, 50]])

array([[10, 20, 30],
       [20, 40, 50]])